### PR TITLE
Principles of retention graphic enchancement

### PR DESCRIPTION
**Pull request by dplotnikov**
https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/842

### CODE REVIEW

**Comment by scanum** [comment]
@stephow-MSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by blouwagie** [comment]
I am not sure I understand the workflow here, but noted that the document itself still does not have a graphic that indicates that legal hold retention rules trump the other retention rules.  See under https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies#the-principles-of-retention-or-what-takes-precedence

**Comment by dplotnikov** [comment]
@blouwagie that's because the PR wasn't merged into master branch yet

**Comment by blouwagie** [comment]
Thank you for your clarification.


Bart Louwagie

**Comment by stephow-MSFT** [comment]
@dplotnikov thanks for the feedback but i'm not sure it's helpful to conflate ediscovery holds with the principles of retention b/c they're a different thing altogether. also, if we did add it, it would have to share #1 position alongside longest deletion period wins.

**Pull request closed without merging**
