### PR TITLE
WIP - Update manage-office-365-message-encryption.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/550
Added note about individual mailbox policies.

### CODE REVIEW

**Comment by scanum** [comment]
@MSFTTracyP Hi! Changes look correct. Could you please confirm and merge? Thanks!!

**Comment by scanum** [comment]
@MSFTTracyP Hi! Any updates on this? Thanks!

**Comment by KCCross** [comment]
Confirmed technical accuracy with engineering - Just getting info from other writers about branding on OWA v Outlook on the web and ActiveSync since those are not my areas. Once I have that, I will likely close this PR and work the addition in from the private repo side. Just a heads-up if you see this PR closed instead of merged.

**Comment by MSFTTracyP** [comment]
May we close this, KCCross?

**Comment by KCCross** [comment]
Yes'm

**Pull request merged**
